import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// components
import Header from "@/components/header";
import Footer from "@/components/footer";
import "./globals.css";

// context wrapper
import { AppContextWrapper } from "@/context/AppContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col xl:h-screen overflow-hidden">
          <Header />
          <main className="flex flex-grow xl:overflow-auto">
            <AppContextWrapper>{children}</AppContextWrapper>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
